/*

DOMANDA 1
UN ALGORITMO È UNA LISTA DI INFORMAZIONI/PROCEDIMENTI CHE SERVONO ALLA REALIZZAZIONE DI UN CERTO PRODOTTO. 

DOMANDA 2
LE VARIABILI SONO DEI CONTENITORI A CUI POSSIAMO ASSEGNARE DEI VALORI E VENGONO UTILIZZATI PER SPOSTARE QUESTI STESSI VALORI DA UN PUNTO A AD UN PUNTO B.

DOMANDA 3
NULL RAPPRESENTA UN CONTENITORE VUOTO MENTRE UNDEFINED ESPLICITA CHE QUEL CONTENITORE NON È STATO ANCORA DEFINITO NEL DOM.

*/